name: Daily Cypress Test

on:
  schedule:
    - cron: '0 0 * * *' # This schedules the workflow to run daily at midnight UTC

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change the Node.js version if needed

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cypress:run
